require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5
